(in-package #:id3-dsl)
(defparameter *v22-frame-names*
  '(("BUF" "Recommended buffer size")
    ("CNT" "Play counter")
    ("COM" "Comments")
    ("CRA" "Audio encryption")
    ("CRM" "Encrypted meta frame")
    ("EQU" "Equalization")
    ("ETC" "Event timing codes")
    ("GEO" "General encapsulated object")
    ("IPL" "Involved people list")
    ("LNK" "Linked information")
    ("MCI" "Music CD Identifier")
    ("MLL" "MPEG location lookup table")
    ("PIC" "Attached picture")
    ("POP" "Popularimeter")
    ("REV" "Reverb")
    ("RVA" "Relative volume adjustment")
    ("SLT" "Synchronized lyric/text")
    ("STC" "Synced tempo codes")
    ("TAL" "Album/Movie/Show title")
    ("TBP" "BPM (Beats Per Minute)")
    ("TCM" "Composer")
    ("TCO" "Content type")
    ("TCR" "Copyright message")
    ("TDA" "Date")
    ("TDY" "Playlist delay")
    ("TEN" "Encoded by")
    ("TFT" "File type")
    ("TIM" "Time")
    ("TKE" "Initial key")
    ("TLA" "Language(s)")
    ("TLE" "Length")
    ("TMT" "Media type")
    ("TOA" "Original artist(s)/performer(s)")
    ("TOF" "Original filename")
    ("TOL" "Original Lyricist(s)/text writer(s)")
    ("TOR" "Original release year")
    ("TOT" "Original album/Movie/Show title")
    ("TP1" "Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group")
    ("TP2" "Band/Orchestra/Accompaniment")
    ("TP3" "Conductor/Performer refinement")
    ("TP4" "Interpreted, remixed, or otherwise modified by")
    ("TPA" "Part of a set")
    ("TPB" "Publisher")
    ("TRC" "ISRC (International Standard Recording Code)")
    ("TRD" "Recording dates")
    ("TRK" "Track number/Position in set")
    ("TSI" "Size")
    ("TSS" "Software/hardware and settings used for encoding")
    ("TT1" "Content group description")
    ("TT2" "Title/Songname/Content description")
    ("TT3" "Subtitle/Description refinement")
    ("TXT" "Lyricist/text writer")
    ("TXX" "User defined text information frame")
    ("TYE" "Year")
    ("UFI" "Unique file identifier")
    ("ULT" "Unsychronized lyric/text transcription")
    ("WAF" "Official audio file webpage")
    ("WAR" "Official artist/performer webpage")
    ("WAS" "Official audio source webpage")
    ("WCM" "Commercial information")
    ("WCP" "Copyright/Legal information")
    ("WPB" "Publishers official webpage")
    ("WXX" "User defined URL link frame")))

;;;; V23 frame names
(defparameter *v23-frame-names*
  '(("AENC" "Audio encryption")
    ("APIC" "Attached picture")
    ("COMM" "Comments")
    ("COMR" "Commercial frame")
    ("ENCR" "Encryption method registration")
    ("EQUA" "Equalization")
    ("ETCO" "Event timing codes")
    ("GEOB" "General encapsulated object")
    ("GRID" "Group identification registration")
    ("IPLS" "Involved people list")
    ("LINK" "Linked information")
    ("MCDI" "Music CD identifier")
    ("MLLT" "MPEG location lookup table")
    ("OWNE" "Ownership frame")
    ("PCNT" "Play counter")
    ("POPM" "Popularimeter")
    ("POSS" "Position synchronisation frame")
    ("PRIV" "Private frame")
    ("RBUF" "Recommended buffer size")
    ("RVAD" "Relative volume adjustment")
    ("RVRB" "Reverb")
    ("SYLT" "Synchronized lyric/text")
    ("SYTC" "Synchronized tempo codes")
    ("TALB" "Album/Movie/Show title")
    ("TBPM" "BPM (beats per minute)")
    ("TCOM" "Composer")
    ("TCON" "Content type")
    ("TCOP" "Copyright message")
    ("TDAT" "Date")
    ("TDLY" "Playlist delay")
    ("TENC" "Encoded by")
    ("TEXT" "Lyricist/Text writer")
    ("TFLT" "File type")
    ("TIME" "Time")
    ("TIT1" "Content group description")
    ("TIT2" "Title/songname/content description")
    ("TIT3" "Subtitle/Description refinement")
    ("TKEY" "Initial key")
    ("TLAN" "Language(s)")
    ("TLEN" "Length")
    ("TMED" "Media type")
    ("TOAL" "Original album/movie/show title")
    ("TOFN" "Original filename")
    ("TOLY" "Original lyricist(s)/text writer(s)")
    ("TOPE" "Original artist(s)/performer(s)")
    ("TORY" "Original release year")
    ("TOWN" "File owner/licensee")
    ("TPE1" "Lead performer(s)/Soloist(s)")
    ("TPE2" "Band/orchestra/accompaniment")
    ("TPE3" "Conductor/performer refinement")
    ("TPE4" "Interpreted, remixed, or otherwise modified by")
    ("TPOS" "Part of a set")
    ("TPUB" "Publisher")
    ("TRCK" "Track number/Position in set")
    ("TRDA" "Recording dates")
    ("TRSN" "Internet radio station name")
    ("TRSO" "Internet radio station owner")
    ("TSIZ" "Size")
    ("TSRC" "ISRC (international standard recording code)")
    ("TSSE" "Software/Hardware and settings used for encoding")
    ("TXXX" "User defined text information frame")
    ("TYER" "Year")
    ("UFID" "Unique file identifier")
    ("USER" "Terms of use")
    ("USLT" "Unsychronized lyric/text transcription")
    ("WCOM" "Commercial information")
    ("WCOP" "Copyright/Legal information")
    ("WOAF" "Official audio file webpage")
    ("WOAR" "Official artist/performer web page")
    ("WOAS" "Official audio source webpage")
    ("WORS" "Official internet radio station homepage")
    ("WPAY" "Payment")
    ("WPUB" "Publishers official webpage")
    ("WXXX" "User defined URL link frame")))

(defparameter *v24-frame-names*
  '(("AENC" "Audio encryption")
    ("APIC" "Attached picture")
    ("ASPI" "Audio seek point index")
    ("COMM" "Comments")
    ("COMR" "Commercial frame")
    ("ENCR" "Encryption method registration")
    ("EQU2" "Equalisation (2)")
    ("ETCO" "Event timing codes")
    ("GEOB" "General encapsulated object")
    ("GRID" "Group identification registration")
    ("LINK" "Linked information")
    ("MCDI" "Music CD identifier")
    ("MLLT" "MPEG location lookup table")
    ("OWNE" "Ownership frame")
    ("PCNT" "Play counter")
    ("POPM" "Popularimeter")
    ("POSS" "Position synchronisation frame")
    ("PRIV" "Private frame")
    ("RBUF" "Recommended buffer size")
    ("RVA2" "Relative volume adjustment (2)")
    ("RVRB" "Reverb")
    ("SEEK" "Seek frame")
    ("SIGN" "Signature frame")
    ("SYLT" "Synchronised lyric/text")
    ("SYTC" "Synchronised tempo codes")
    ("TALB" "Album/Movie/Show title")
    ("TBPM" "BPM (beats per minute)")
    ("TCOM" "Composer")
    ("TCON" "Content type")
    ("TCOP" "Copyright message")
    ("TDEN" "Encoding time")
    ("TDLY" "Playlist delay")
    ("TDOR" "Original release time")
    ("TDRC" "Recording time")
    ("TDRL" "Release time")
    ("TDTG" "Tagging time")
    ("TENC" "Encoded by")
    ("TEXT" "Lyricist/Text writer")
    ("TFLT" "File type")
    ("TIPL" "Involved people list")
    ("TIT1" "Content group description")
    ("TIT2" "Title/songname/content description")
    ("TIT3" "Subtitle/Description refinement")
    ("TKEY" "Initial key")
    ("TLAN" "Language(s)")
    ("TLEN" "Length")
    ("TMCL" "Musician credits list")
    ("TMED" "Media type")
    ("TMOO" "Mood")
    ("TOAL" "Original album/movie/show title")
    ("TOFN" "Original filename")
    ("TOLY" "Original lyricist(s)/text writer(s)")
    ("TOPE" "Original artist(s)/performer(s)")
    ("TOWN" "File owner/licensee")
    ("TPE1" "Lead performer(s)/Soloist(s)")
    ("TPE2" "Band/orchestra/accompaniment")
    ("TPE3" "Conductor/performer refinement")
    ("TPE4" "Interpreted, remixed, or otherwise modified by")
    ("TPOS" "Part of a set")
    ("TPRO" "Produced notice")
    ("TPUB" "Publisher")
    ("TRCK" "Track number/Position in set")
    ("TRSN" "Internet radio station name")
    ("TRSO" "Internet radio station owner")
    ("TSOA" "Album sort order")
    ("TSOP" "Performer sort order")
    ("TSOT" "Title sort order")
    ("TSRC" "ISRC (international standard recording code)")
    ("TSSE" "Software/Hardware and settings used for encoding")
    ("TSST" "Set subtitle")
    ("TXXX" "User defined text information frame")
    ("UFID" "Unique file identifier")
    ("USER" "Terms of use")
    ("USLT" "Unsynchronised lyric/text transcription")
    ("WCOM" "Commercial information")
    ("WCOP" "Copyright/Legal information")
    ("WOAF" "Official audio file webpage")
    ("WOAR" "Official artist/performer webpage")
    ("WOAS" "Official audio source webpage")
    ("WORS" "Official Internet radio station homepage")
    ("WPAY" "Payment")
    ("WPUB" "Publishers official webpage")
    ("WXXX" "User defined URL link frame")))

(defstruct frame-db-entry text is-v22 is-v23 is-v24 nil)

(defparameter *frame-db* nil)

(defmacro make-frame-db ()
  `(progn
     (setf *frame-db* (make-hash-table :test #'equalp))
     (dolist (s *v22-frame-names*)
       (setf (gethash (first s) *frame-db*)
             (make-frame-db-entry :text (second s) :is-v22 t)))
     (dolist (s *v23-frame-names*)
       (setf (gethash (first s) *frame-db*)
             (make-frame-db-entry :text (second s) :is-v23 t)))
     (dolist (s *v24-frame-names*)
       (multiple-value-bind (val found) (gethash (first s) *frame-db*)
         (setf (gethash (first s) *frame-db*)
               (if found
                   (progn
                     (setf (frame-db-entry-is-v24 val) t)
                     val)
                   (make-frame-db-entry :text (second s) :is-v24 t)))))))
(make-frame-db)
#+CCL
(defun coverage-test ()
  "For development only: loops through the *frame-db* and tells which frames are not-implmented yet"

  (let ((count 0))
    (maphash (lambda (k v)
               (declare (ignore v))
               (let* ((str (mk-frame-class-name k))
                      (class (find-class (find-symbol str) nil))
                      (super-name (if class (class-name (first (ccl::class-direct-superclasses class))))))

                 (if (null class)
                     (progn
                       (incf count)
                       (format t "~a:: not implemented yet~%" str))
                     (if (or (string= super-name "RAW-FRAME-V2.2")
                             (string= super-name "RAW-FRAME-V2.3")
                             (string= super-name "RAW-FRAME-V2.4"))
                         (format t "~2t~a:: RAW~%" (class-name class))))))
             *frame-db*)
    (format t "~:d frames not yet implemented~%" count)))

(defun get-frame-db-entry (id)
  "Given a frame id/name, return the associated FRAME-DB-ENTRY"
  (gethash id *frame-db*))

(defun whats-the-diff? ()
  (format t "Frames defined in 2.3, but not 2.4:~%")
  (maphash (lambda (k v)
             (if (and (frame-db-entry-is-v23 v) (not (frame-db-entry-is-v24 v)))
                 (format t "  ~a~%" k))) *frame-db*)
  (format t "Frames defined in 2.4, but not 2.3:~%")
  (maphash (lambda (k v)
             (if (and (frame-db-entry-is-v24 v) (not (frame-db-entry-is-v23 v)))
                 (format t "  ~a~%" k))) *frame-db*))
